trigger:
  branches:
    include: [main, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v2.4.2

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py37, py38]
    os: linux
    coverage: false
